apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: travelo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BilalZiyane1/travelo-k8s-manifests.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: travelo
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
